window:
  opacity: 0.65
  padding:
    x: 5
    y: 5
  decorations: full

font:
  # normal:
  # family: Iosevka
  # bold:
  # italic:
  # bold_italic:
  size: 12


colors:
  primary:
    background: '#000000'
    foreground: '#c5c8c6'
