#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xsetroot -cursor_name left_ptr

# setup external monitors 



if [[ $(xrandr -q | grep 'HDMI-1 connected') && $(xrandr -q | grep '2560x1440')  ]]; then
  xrandr --output eDP-1 --mode 1920x1080 --rotate normal --dpi 138 --output HDMI-1 --mode 2560x1440 --rotate normal --right-of eDP-1 --dpi 128 --scale 1x1
elif [[ $(xrandr -q | grep 'HDMI-1 connected') ]]; then
  xrandr --output eDP-1 --mode 1920x1080 --rotate normal --dpi 138 --output HDMI-1 --mode 1920x1080 --rotate normal --right-of eDP-1 --dpi 96
else
  xrandr --output eDP-1 --mode 1920x1080 --rotate normal --dpi 138 --output HDMI-1 --off
fi

bspc monitor HDMI-1 -d 1 2 3 4 5
bspc monitor eDP-1 -d 1 2 3 4 5

# additional services
$HOME/.config/polybar/launch.sh
killall -q dunst
dunst

# setup default configuration

bspc config border_width         2
bspc config window_gap           10
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=tiled follow=on
bspc rule -a irefox desktop='^2' state=tiled follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# RANDOM RULES
bspc rule -a Spotify desktop='^8'
bspc rule -a Pavucontrol state=floating

